### ISSUE TITLE
Deribit gateway strange behaviour  

### ISSUE THREAD

**Issue by IlyaKrotov** [roq-trading/roq-feedback#3]
Hello again, 

I downloaded the last version of deribit gateway and tried to run it not with test endpoints. It worked before, but now I've got very strange error. It starts to download snapshots, but then it prints the following:

```
I0326 10:16:21.709288 3924 tcp_ssl_connection.cpp:47] Connecting to host="deribit.com", port=443
I0326 10:16:26.738507 3924 socket.cpp:83] Sending upgrade request (path="ws/api/v2")
I0326 10:16:26.742060 3924 socket.cpp:242] HTTP response status=301 text="Moved Permanently"
E0326 10:16:26.742147 3924 tcp_ssl_connection.cpp:80] Exception: what="Expected status code 101 (Switching Protocols),got status code 301 (MOVED_PERMANENTLY)"
W0326 10:16:26.742199 3924 tcp_ssl_connection.cpp:93] Disconnected
```

This is how I start gateway

```
ROQ_v=1 roq-deribit --name "deribit" --config-file deribit.toml --listen ~/deribit.sock --ws_uri "wss://deribit.com/ws/api/v2" --fix_uri "tcp://www.deribit.com:9880"
```

**Comment by IlyaKrotov** [comment]
By the way, v1 API doesn't work too

**Comment by thraneh** [comment]
Your command line looks fine.

Just to understand better: did you use `conda update`?

I have always suspected that conda doesn't correctly force-update the dependencies.
That's why I suggested recreating the conda environment from scratch.

I have just installed everything from scratch and it seems to work fine.

Could you let me know if that works for you too, please?

PS The intention is to have users source packages from the `stable` channel (you're using `unstable`): we will never republish packages with similar version numbers into the stable channel and the issue (that I suspect) should never cause problems then.

**Comment by thraneh** [comment]
Have a look [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#id1) to find out how to create parallel conda environments.

If you want to test something new, you should be able to create a new environment without touching what already works for you.

**Comment by IlyaKrotov** [comment]
I created new conda env and installed gateway again when I experienced this, before creating the issue. Now I did it again and experienced the same problem.

**Comment by thraneh** [comment]
So that's my mistake -- the documentation was wrong. My apologies.

You have to use `--ws_uri "wss://www.deribit.com/ws/api/v2"` (notice the `www.` prefix).

If it works now, you'll probably see lots of bad login requests (I was in the middle of extending with WebSocket support, but it's not ready yet).

I have pushed a new version completely disabling the WebSocket. I will make sure to only push when it's working properly.

**Comment by IlyaKrotov** [comment]
This is strange because I've found out that even with this error it consumes data

```
I0326 11:09:37.832781 6279 tcp_ssl_connection.cpp:47] Connecting to host="deribit.com", port=443
I0326 11:09:37.887805 6279 socket.cpp:83] Sending upgrade request (path="ws/api/v2")
I0326 11:09:37.891515 6279 socket.cpp:242] HTTP response status=301 text="Moved Permanently"
E0326 11:09:37.891741 6279 tcp_ssl_connection.cpp:80] Exception: what="Expected status code 101 (Switching Protocols),got status code 301 (MOVED_PERMANENTLY)"
W0326 11:09:37.891959 6279 tcp_ssl_connection.cpp:93] Disconnected
I0326 11:09:48.061514 6278 controller.cpp:201] Synchronize event log ...
I0326 11:09:48.085462 6278 producer.cpp:241] Write 476482 byte(s) (consumed=2457920 produced=476484 ratio=0.19)
I0326 11:10:09.892137 6279 tcp_ssl_connection.cpp:47] Connecting to host="deribit.com", port=443
I0326 11:10:09.949162 6279 socket.cpp:83] Sending upgrade request (path="ws/api/v2")
I0326 11:10:09.952867 6279 socket.cpp:242] HTTP response status=301 text="Moved Permanently"
E0326 11:10:09.953117 6279 tcp_ssl_connection.cpp:80] Exception: what="Expected status code 101 (Switching Protocols),got status code 301 (MOVED_PERMANENTLY)"
W0326 11:10:09.953354 6279 tcp_ssl_connection.cpp:93] Disconnected
```

**Comment by IlyaKrotov** [comment]
And it works now, thanks!

**Comment by thraneh** [comment]
That's because the gateway establishes multiple connections to the exchange.

Deribit provides most information over FIX, including market data, positions, etc.

Their WebSocket interface provides more information. I was in the middle of working on that when you highlighted your show-stopper (the issue with commissions).

Again, apologies for not being properly prepared for this situation. I will try to isolate development a bit more going forward.

**Comment by IlyaKrotov** [comment]
You're doing really great work, thanks!
